// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- OpenNext documents this generated worker import with @ts-ignore.
// @ts-ignore `.open-next/worker.js` is generated by OpenNext before Wrangler builds this entry.
import openNextWorker from './.open-next/worker.js'

const IMAGE_CACHE_TTL_SECONDS = 60 * 60 * 24 * 30
const IMAGE_CACHE_CONTROL = `public, max-age=${IMAGE_CACHE_TTL_SECONDS}`
const NEXT_IMAGE_PATHNAME = '/_next/image'
const IMAGE_FORMAT_CACHE_PARAM = '__ehentai_image_format'

type ImageFormatVariant = 'avif' | 'webp' | 'source'

type CloudflareCacheStorage = CacheStorage & {
  readonly default: Cache
}

export default {
  // 图片 URL 基本不变，只在 Next image optimizer 外层补边缘与浏览器缓存。
  async fetch(request, env, ctx) {
    if (request.method !== 'GET' || !isNextImageRequest(request)) {
      return openNextWorker.fetch(request, env, ctx)
    }

    const imageCache = getDefaultCache()
    const cacheKey = createImageCacheKey(request)
    const cachedResponse = await imageCache.match(cacheKey)

    if (cachedResponse) {
      return cachedResponse
    }

    const response = await openNextWorker.fetch(request, env, ctx)

    if (!isCacheableImageResponse(response)) {
      return response
    }

    const cacheableResponse = new Response(response.body, response)
    cacheableResponse.headers.set('Cache-Control', IMAGE_CACHE_CONTROL)
    ctx.waitUntil(imageCache.put(cacheKey, cacheableResponse.clone()))

    return cacheableResponse
  },
} satisfies ExportedHandler<CloudflareEnv>

function isNextImageRequest(request: Request): boolean {
  return new URL(request.url).pathname === NEXT_IMAGE_PATHNAME
}

// Next build 会优先看到 DOM CacheStorage；Cloudflare Workers 运行时额外提供 default cache。
function getDefaultCache(): Cache {
  return (caches as CloudflareCacheStorage).default
}

// Cache API 的 key 主要看 URL，所以把 Accept 支持的格式类别折进内部 key。
function createImageCacheKey(request: Request): Request {
  const cacheKeyUrl = new URL(request.url)
  cacheKeyUrl.searchParams.set(
    IMAGE_FORMAT_CACHE_PARAM,
    getImageFormatVariant(request.headers.get('Accept')),
  )

  return new Request(cacheKeyUrl.toString(), request)
}

function getImageFormatVariant(acceptHeader: string | null): ImageFormatVariant {
  const accept = acceptHeader?.toLowerCase() ?? ''

  if (accept.includes('image/avif')) {
    return 'avif'
  }

  if (accept.includes('image/webp')) {
    return 'webp'
  }

  return 'source'
}

function isCacheableImageResponse(response: Response): boolean {
  return (
    response.status >= 200
    && response.status < 300
    && response.status !== 206
    && response.headers.get('Content-Type')?.toLowerCase().startsWith('image/') === true
  )
}

// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- OpenNext documents this generated worker re-export with @ts-ignore.
// @ts-ignore `.open-next/worker.js` is generated by OpenNext before Wrangler builds this entry.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'
