name = "ehentai-toplist-archive-web"
main = ".open-next/worker.js"
compatibility_date = "2024-12-08"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = false
assets.directory = ".open-next/assets"
assets.binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "ehentai-toplist-archive"
database_id = "48fbbd89-2ea8-4543-b6b8-cb5ca5d6d805"
remote = true

[[routes]]
pattern = "ehentai-toplist-archive.com"
custom_domain = true