name = "ehentai-toplist-archive-crawler"
main = "src/index.ts"
compatibility_date = "2025-09-17"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

[limits]
cpu_ms = 600_000

[triggers]
crons = ["0 0 * * *"]